import type { AgentStep } from './types';

export const INITIAL_AGENT_STEPS: AgentStep[] = [
  { step: 1, agent_name: 'Profile Agent', status: 'idle', message: 'Waiting...', logs: [] },
  { step: 2, agent_name: 'Document Verifier', status: 'idle', message: 'Waiting...', logs: [] },
  { step: 3, agent_name: 'Scheme Discovery', status: 'idle', message: 'Waiting...', logs: [] },
  { step: 4, agent_name: 'Eligibility Checker', status: 'idle', message: 'Waiting...', logs: [] },
  { step: 5, agent_name: 'Deep Eligibility', status: 'idle', message: 'Waiting...', logs: [] },
  { step: 6, agent_name: 'Application Filler', status: 'idle', message: 'Waiting...', logs: [] },
  { step: 7, agent_name: 'Narrator Agent', status: 'idle', message: 'Waiting...', logs: [] },
];

export const INDIAN_STATES = [
  'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh',
  'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand', 'Karnataka',
  'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram',
  'Nagaland', 'Odisha', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu',
  'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal',
  'Andaman & Nicobar', 'Chandigarh', 'Dadra & Nagar Haveli', 'Daman & Diu',
  'Delhi', 'Jammu & Kashmir', 'Ladakh', 'Lakshadweep', 'Puducherry',
];

export const SCHEME_CATEGORIES = [
  { id: 'agriculture', label: 'Agriculture', icon: 'Wheat', count: 247 },
  { id: 'education', label: 'Education', icon: 'GraduationCap', count: 189 },
  { id: 'health', label: 'Health', icon: 'Heart', count: 156 },
  { id: 'housing', label: 'Housing', icon: 'Home', count: 98 },
  { id: 'employment', label: 'Employment', icon: 'Briefcase', count: 134 },
  { id: 'women', label: 'Women & Child', icon: 'Users', count: 112 },
  { id: 'disability', label: 'Disability', icon: 'Accessibility', count: 67 },
  { id: 'senior', label: 'Senior Citizens', icon: 'UserCheck', count: 45 },
] as const;

export const TRANSLATIONS = {
  en: {
    'nav.home': 'Home',
    'nav.schemes': 'Browse Schemes',
    'nav.how': 'How It Works',
    'nav.signin': 'Sign In',
    'nav.getstarted': 'Get Started',
    'nav.dashboard': 'Dashboard',
    'hero.eyebrow': 'Powered by AI · Built for Bharat',
    'hero.headline': 'Find Every Scheme You Deserve',
    'hero.subtext': 'Our AI agents scan 1,200+ government welfare schemes and match them to your exact profile — in under 60 seconds.',
    'hero.cta.primary': 'Start for Free',
    'hero.cta.secondary': 'Browse All Schemes',
    'hero.aadhaar': 'Aadhaar Secured',
    'hero.scheme_count': '1,200+ Schemes',
    'hero.languages': '12 Languages',
    'hero.beneficiaries': '48 Lakh Beneficiaries',
    'stats.schemes': 'Schemes',
    'stats.benefits': 'Benefits Unlocked',
    'stats.citizens': 'Citizens Helped',
    'stats.agents': 'AI Agents Working',
    'dashboard.greeting.morning': 'Good morning',
    'dashboard.greeting.afternoon': 'Good afternoon',
    'dashboard.greeting.evening': 'Good evening',
    'dashboard.eligible_for': 'You are eligible for',
    'dashboard.schemes': 'schemes',
    'dashboard.worth': 'worth',
    'dashboard.in_annual': 'in annual benefits',
    'dashboard.run_ai': 'Run Full AI Analysis',
    'dashboard.eligible_schemes': 'Eligible Schemes',
    'dashboard.applied': 'Applied',
    'dashboard.pending': 'Pending Approval',
    'dashboard.total_benefits': 'Total Benefits',
    'dashboard.recommended': 'Recommended Schemes',
    'dashboard.view_all': 'View All',
    'dashboard.complete_profile': 'Complete Your Profile',
    'dashboard.complete_profile_desc': 'We need your details to find schemes for you.',
    'dashboard.create_profile': 'Create Profile',
    'dashboard.doc_vault': 'Document Vault',
    'dashboard.doc_vault_desc': 'Upload your ID proofs (Aadhaar, PAN) directly to secure cloud storage.',
    'dashboard.upload_id': 'Upload ID Proof',
    'dashboard.uploading': 'Uploading...',
    'dashboard.schemes_found': 'schemes found',
    'dashboard.discovering': 'Discovering schemes...',
    'dashboard.loading': 'Loading schemes...',
    'dashboard.authenticating': 'Authenticating...',
    'scheme.eligible': 'Eligible',
    'scheme.not_eligible': 'Not eligible',
    'scheme.apply_now': 'Apply Now',
    'scheme.view_details': 'View Details',
    'agent.title': 'CivicAI Intelligence Pipeline',
    'agent.subtitle': '7-agent AI pipeline for welfare scheme matching',
    'agent.run': 'Run AI Analysis',
    'agent.running': 'Analyzing...',
    'agent.register_first': 'Register First',
    'agent.complete': 'Complete',
    'agent.analysis_complete': 'Analysis Complete',
    'agent.schemes_eligible': 'schemes eligible',
    'agent.total_estimated': 'Total estimated annual benefits',
    'register.title': 'Create Account',
    'register.subtitle': 'Fill in your details to get started',
    'register.name': 'Full Name',
    'register.email': 'Email',
    'register.mobile': 'Mobile Number',
    'register.dob': 'Date of Birth',
    'register.state': 'State',
    'register.district': 'District',
    'register.gender': 'Gender',
    'register.category': 'Category',
    'register.occupation': 'Occupation',
    'register.income': 'Annual Household Income',
    'register.land': 'Do you own agricultural land?',
    'register.bpl': 'Do you have a BPL card?',
    'register.disability': 'Are you a differently-abled person?',
    'register.submit': 'Create My Account',
    'register.creating': 'Creating Profile...',
    'register.already_have': 'Already have an account?',
    'register.step1': 'Personal Details',
    'register.find_schemes': 'Find My Schemes',
    'login.title': 'Welcome back',
    'login.subtitle': 'Sign in to access your dashboard',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.forgot': 'Forgot Password?',
    'login.signin': 'Sign In',
    'login.signing_in': 'Signing In...',
    'login.new_user': 'New to CivicAI?',
    'login.create_account': 'Create Account',
    'login.join': 'Join 48 lakh+ citizens already using CivicAI',
    'how.title': 'Three steps to your benefits',
    'how.step1.title': 'Tell us about yourself',
    'how.step1.desc': 'Fill in your basic details — state, income, occupation, and documents. Takes about 2 minutes.',
    'how.step1.badge': '~2 min',
    'how.step2.title': 'AI finds your schemes',
    'how.step2.desc': 'Our 7 AI agents scan 1,200+ schemes across 58 ministries and match them to your exact profile.',
    'how.step2.badge': '7 agents working',
    'how.step3.title': 'Apply with guidance',
    'how.step3.desc': 'Get step-by-step application help, auto-filled forms, and document checklist for every eligible scheme.',
    'how.step3.badge': 'Document vault included',
    'footer.quick_links': 'Quick Links',
    'footer.categories': 'Scheme Categories',
    'footer.contact': 'Contact',
    'footer.description': 'Autonomous AI welfare intelligence system helping rural Indian citizens discover and apply for government schemes.',
    'footer.copyright': '© 2025 CivicAI | Developed under Digital India Initiative | Government of India',
    'footer.disclaimer': 'Disclaimer: This platform provides information on government welfare schemes. All scheme details are sourced from official government databases.',
  },
  hi: {
    'nav.home': 'होम',
    'nav.schemes': 'योजनाएं देखें',
    'nav.how': 'कैसे काम करता है',
    'nav.signin': 'साइन इन',
    'nav.getstarted': 'शुरू करें',
    'nav.dashboard': 'डैशबोर्ड',
    'hero.eyebrow': 'AI द्वारा संचालित · भारत के लिए निर्मित',
    'hero.headline': 'अपनी हर योजना खोजें',
    'hero.subtext': 'हमारे AI एजेंट 1,200+ सरकारी कल्याणकारी योजनाओं को स्कैन करते हैं और 60 सेकंड से कम समय में आपकी प्रोफ़ाइल से मिलान करते हैं।',
    'hero.cta.primary': 'मुफ्त शुरू करें',
    'hero.cta.secondary': 'सभी योजनाएं देखें',
    'hero.aadhaar': 'आधार सुरक्षित',
    'hero.scheme_count': '1,200+ योजनाएं',
    'hero.languages': '12 भाषाएं',
    'hero.beneficiaries': '48 लाख लाभार्थी',
    'stats.schemes': 'योजनाएं',
    'stats.benefits': 'लाभ अनलॉक',
    'stats.citizens': 'नागरिकों की मदद',
    'stats.agents': 'AI एजेंट कार्यरत',
    'dashboard.greeting.morning': 'सुप्रभात',
    'dashboard.greeting.afternoon': 'नमस्कार',
    'dashboard.greeting.evening': 'शुभ संध्या',
    'dashboard.eligible_for': 'आप पात्र हैं',
    'dashboard.schemes': 'योजनाओं',
    'dashboard.worth': 'मूल्य',
    'dashboard.in_annual': 'वार्षिक लाभ में',
    'dashboard.run_ai': 'पूर्ण AI विश्लेषण चलाएं',
    'dashboard.eligible_schemes': 'पात्र योजनाएं',
    'dashboard.applied': 'आवेदित',
    'dashboard.pending': 'स्वीकृति लंबित',
    'dashboard.total_benefits': 'कुल लाभ',
    'dashboard.recommended': 'अनुशंसित योजनाएं',
    'dashboard.view_all': 'सभी देखें',
    'dashboard.complete_profile': 'अपनी प्रोफ़ाइल पूरी करें',
    'dashboard.complete_profile_desc': 'योजनाएं खोजने के लिए हमें आपकी जानकारी चाहिए।',
    'dashboard.create_profile': 'प्रोफ़ाइल बनाएं',
    'dashboard.doc_vault': 'दस्तावेज़ वॉल्ट',
    'dashboard.doc_vault_desc': 'अपने पहचान प्रमाण (आधार, पैन) सीधे सुरक्षित क्लाउड स्टोरेज में अपलोड करें।',
    'dashboard.upload_id': 'पहचान प्रमाण अपलोड करें',
    'dashboard.uploading': 'अपलोड हो रहा है...',
    'dashboard.schemes_found': 'योजनाएं मिलीं',
    'dashboard.discovering': 'योजनाएं खोज रहे हैं...',
    'dashboard.loading': 'योजनाएं लोड हो रही हैं...',
    'dashboard.authenticating': 'प्रमाणीकरण...',
    'scheme.eligible': 'पात्र',
    'scheme.not_eligible': 'अपात्र',
    'scheme.apply_now': 'अभी आवेदन करें',
    'scheme.view_details': 'विवरण देखें',
    'agent.title': 'CivicAI इंटेलिजेंस पाइपलाइन',
    'agent.subtitle': 'कल्याण योजना मिलान के लिए 7-एजेंट AI पाइपलाइन',
    'agent.run': 'AI विश्लेषण चलाएं',
    'agent.running': 'विश्लेषण हो रहा है...',
    'agent.register_first': 'पहले रजिस्टर करें',
    'agent.complete': 'पूर्ण',
    'agent.analysis_complete': 'विश्लेषण पूर्ण',
    'agent.schemes_eligible': 'योजनाएं पात्र',
    'agent.total_estimated': 'कुल अनुमानित वार्षिक लाभ',
    'register.title': 'खाता बनाएं',
    'register.subtitle': 'शुरू करने के लिए अपना विवरण भरें',
    'register.name': 'पूरा नाम',
    'register.email': 'ईमेल',
    'register.mobile': 'मोबाइल नंबर',
    'register.dob': 'जन्म तिथि',
    'register.state': 'राज्य',
    'register.district': 'जिला',
    'register.gender': 'लिंग',
    'register.category': 'श्रेणी',
    'register.occupation': 'व्यवसाय',
    'register.income': 'वार्षिक घरेलू आय',
    'register.land': 'क्या आपके पास कृषि भूमि है?',
    'register.bpl': 'क्या आपके पास BPL कार्ड है?',
    'register.disability': 'क्या आप दिव्यांग हैं?',
    'register.submit': 'मेरा खाता बनाएं',
    'register.creating': 'प्रोफ़ाइल बना रहे हैं...',
    'register.already_have': 'पहले से खाता है?',
    'register.step1': 'व्यक्तिगत विवरण',
    'register.find_schemes': 'मेरी योजनाएं खोजें',
    'login.title': 'वापस स्वागत है',
    'login.subtitle': 'अपने डैशबोर्ड तक पहुंचने के लिए साइन इन करें',
    'login.email': 'ईमेल',
    'login.password': 'पासवर्ड',
    'login.forgot': 'पासवर्ड भूल गए?',
    'login.signin': 'साइन इन',
    'login.signing_in': 'साइन इन हो रहा है...',
    'login.new_user': 'CivicAI में नए हैं?',
    'login.create_account': 'खाता बनाएं',
    'login.join': '48 लाख+ नागरिक पहले से CivicAI का उपयोग कर रहे हैं',
    'how.title': 'आपके लाभों तक तीन कदम',
    'how.step1.title': 'अपने बारे में बताएं',
    'how.step1.desc': 'अपना बुनियादी विवरण भरें — राज्य, आय, व्यवसाय और दस्तावेज़। लगभग 2 मिनट लगते हैं।',
    'how.step1.badge': '~2 मिनट',
    'how.step2.title': 'AI आपकी योजनाएं खोजता है',
    'how.step2.desc': 'हमारे 7 AI एजेंट 58 मंत्रालयों की 1,200+ योजनाओं को स्कैन करते हैं और आपकी प्रोफ़ाइल से मिलान करते हैं।',
    'how.step2.badge': '7 एजेंट कार्यरत',
    'how.step3.title': 'मार्गदर्शन के साथ आवेदन करें',
    'how.step3.desc': 'हर पात्र योजना के लिए चरण-दर-चरण आवेदन सहायता, ऑटो-भरे फॉर्म और दस्तावेज़ चेकलिस्ट प्राप्त करें।',
    'how.step3.badge': 'दस्तावेज़ वॉल्ट शामिल',
    'footer.quick_links': 'त्वरित लिंक',
    'footer.categories': 'योजना श्रेणियां',
    'footer.contact': 'संपर्क',
    'footer.description': 'ग्रामीण भारतीय नागरिकों को सरकारी योजनाओं की खोज और आवेदन में मदद करने वाली स्वायत्त AI कल्याण खुफिया प्रणाली।',
    'footer.copyright': '© 2025 CivicAI | डिजिटल इंडिया पहल के तहत विकसित | भारत सरकार',
    'footer.disclaimer': 'अस्वीकरण: यह प्लेटफॉर्म सरकारी कल्याण योजनाओं की जानकारी प्रदान करता है। सभी योजना विवरण आधिकारिक सरकारी डेटाबेस से प्राप्त हैं।',
  },
  mr: {
    'nav.home': 'मुख्यपृष्ठ',
    'nav.schemes': 'योजना पहा',
    'nav.how': 'कसे कार्य करते',
    'nav.signin': 'साइन इन',
    'nav.getstarted': 'सुरू करा',
    'nav.dashboard': 'डॅशबोर्ड',
    'hero.eyebrow': 'AI द्वारे संचालित · भारतासाठी बनवलेले',
    'hero.headline': 'तुमच्या प्रत्येक योजना शोधा',
    'hero.subtext': 'आमचे AI एजंट 1,200+ सरकारी कल्याणकारी योजना स्कॅन करतात आणि 60 सेकंदांत तुमच्या प्रोफाइलशी जुळवतात.',
    'hero.cta.primary': 'मोफत सुरू करा',
    'hero.cta.secondary': 'सर्व योजना पहा',
    'hero.aadhaar': 'आधार सुरक्षित',
    'hero.scheme_count': '1,200+ योजना',
    'hero.languages': '12 भाषा',
    'hero.beneficiaries': '48 लाख लाभार्थी',
    'stats.schemes': 'योजना',
    'stats.benefits': 'लाभ अनलॉक',
    'stats.citizens': 'नागरिकांना मदत',
    'stats.agents': 'AI एजंट कार्यरत',
    'dashboard.greeting.morning': 'सुप्रभात',
    'dashboard.greeting.afternoon': 'नमस्कार',
    'dashboard.greeting.evening': 'शुभ संध्याकाळ',
    'dashboard.eligible_for': 'तुम्ही पात्र आहात',
    'dashboard.schemes': 'योजनांसाठी',
    'dashboard.worth': 'मूल्य',
    'dashboard.in_annual': 'वार्षिक लाभांत',
    'dashboard.run_ai': 'पूर्ण AI विश्लेषण चालवा',
    'dashboard.eligible_schemes': 'पात्र योजना',
    'dashboard.applied': 'अर्ज केलेले',
    'dashboard.pending': 'मंजुरी प्रलंबित',
    'dashboard.total_benefits': 'एकूण लाभ',
    'dashboard.recommended': 'शिफारस केलेल्या योजना',
    'dashboard.view_all': 'सर्व पहा',
    'dashboard.complete_profile': 'तुमची प्रोफाइल पूर्ण करा',
    'dashboard.complete_profile_desc': 'योजना शोधण्यासाठी आम्हाला तुमची माहिती हवी आहे.',
    'dashboard.create_profile': 'प्रोफाइल तयार करा',
    'dashboard.doc_vault': 'दस्तऐवज वॉल्ट',
    'dashboard.doc_vault_desc': 'तुमचे ओळखपत्र (आधार, पॅन) सुरक्षित क्लाउड स्टोरेजमध्ये अपलोड करा.',
    'dashboard.upload_id': 'ओळखपत्र अपलोड करा',
    'dashboard.uploading': 'अपलोड होत आहे...',
    'dashboard.schemes_found': 'योजना सापडल्या',
    'dashboard.discovering': 'योजना शोधत आहोत...',
    'dashboard.loading': 'योजना लोड होत आहेत...',
    'dashboard.authenticating': 'प्रमाणीकरण...',
    'scheme.eligible': 'पात्र',
    'scheme.not_eligible': 'अपात्र',
    'scheme.apply_now': 'आता अर्ज करा',
    'scheme.view_details': 'तपशील पहा',
    'agent.title': 'CivicAI इंटेलिजन्स पाइपलाइन',
    'agent.subtitle': 'कल्याण योजना जुळवणीसाठी 7-एजंट AI पाइपलाइन',
    'agent.run': 'AI विश्लेषण चालवा',
    'agent.running': 'विश्लेषण सुरू आहे...',
    'agent.register_first': 'प्रथम नोंदणी करा',
    'agent.complete': 'पूर्ण',
    'agent.analysis_complete': 'विश्लेषण पूर्ण',
    'agent.schemes_eligible': 'योजना पात्र',
    'agent.total_estimated': 'एकूण अंदाजित वार्षिक लाभ',
    'register.title': 'खाते तयार करा',
    'register.subtitle': 'सुरू करण्यासाठी तुमचे तपशील भरा',
    'register.name': 'पूर्ण नाव',
    'register.email': 'ईमेल',
    'register.mobile': 'मोबाइल नंबर',
    'register.dob': 'जन्मतारीख',
    'register.state': 'राज्य',
    'register.district': 'जिल्हा',
    'register.gender': 'लिंग',
    'register.category': 'वर्ग',
    'register.occupation': 'व्यवसाय',
    'register.income': 'वार्षिक घरगुती उत्पन्न',
    'register.land': 'तुमच्याकडे शेतजमीन आहे का?',
    'register.bpl': 'तुमच्याकडे BPL कार्ड आहे का?',
    'register.disability': 'तुम्ही दिव्यांग आहात का?',
    'register.submit': 'माझे खाते तयार करा',
    'register.creating': 'प्रोफाइल तयार होत आहे...',
    'register.already_have': 'आधीपासून खाते आहे?',
    'register.step1': 'वैयक्तिक तपशील',
    'register.find_schemes': 'माझ्या योजना शोधा',
    'login.title': 'परत स्वागत',
    'login.subtitle': 'तुमच्या डॅशबोर्डवर प्रवेश करण्यासाठी साइन इन करा',
    'login.email': 'ईमेल',
    'login.password': 'पासवर्ड',
    'login.forgot': 'पासवर्ड विसरलात?',
    'login.signin': 'साइन इन',
    'login.signing_in': 'साइन इन होत आहे...',
    'login.new_user': 'CivicAI वर नवीन आहात?',
    'login.create_account': 'खाते तयार करा',
    'login.join': '48 लाख+ नागरिक आधीपासून CivicAI वापरत आहेत',
    'how.title': 'तुमच्या लाभांपर्यंत तीन पायऱ्या',
    'how.step1.title': 'स्वतःबद्दल सांगा',
    'how.step1.desc': 'तुमचे मूलभूत तपशील भरा — राज्य, उत्पन्न, व्यवसाय आणि दस्तऐवज. सुमारे 2 मिनिटे लागतात.',
    'how.step1.badge': '~2 मिनिटे',
    'how.step2.title': 'AI तुमच्या योजना शोधतो',
    'how.step2.desc': 'आमचे 7 AI एजंट 58 मंत्रालयांच्या 1,200+ योजना स्कॅन करतात आणि तुमच्या प्रोफाइलशी जुळवतात.',
    'how.step2.badge': '7 एजंट कार्यरत',
    'how.step3.title': 'मार्गदर्शनासह अर्ज करा',
    'how.step3.desc': 'प्रत्येक पात्र योजनेसाठी चरण-दर-चरण अर्ज मदत, ऑटो-भरलेले फॉर्म आणि दस्तऐवज चेकलिस्ट मिळवा.',
    'how.step3.badge': 'दस्तऐवज वॉल्ट समाविष्ट',
    'footer.quick_links': 'जलद दुवे',
    'footer.categories': 'योजना वर्ग',
    'footer.contact': 'संपर्क',
    'footer.description': 'ग्रामीण भारतीय नागरिकांना सरकारी योजना शोधण्यात आणि अर्ज करण्यात मदत करणारी स्वायत्त AI कल्याण बुद्धिमत्ता प्रणाली.',
    'footer.copyright': '© 2025 CivicAI | डिजिटल इंडिया उपक्रमांतर्गत विकसित | भारत सरकार',
    'footer.disclaimer': 'अस्वीकरण: हे प्लॅटफॉर्म सरकारी कल्याण योजनांची माहिती प्रदान करते. सर्व योजना तपशील अधिकृत सरकारी डेटाबेसमधून प्राप्त आहेत.',
  },
} as const;
